# The OpenFaaS OIDC Proxy is part of Actuated
#
# A subscription license is required for actuated, learn more at
# https://actuated.dev

# You will need to create a license named "actuated-license" - see the
# chart README for detailed instructions.

# Comma separated list of repository owners for which short-lived OIDC tokens are authorized.
# Each item can be an individual user or an organization.
# For example: "alexellis,self-actuated"
repositoryOwners: ""

# The public URL to access the proxy
# i.e. https://oidc-proxy.example.com
publicURL: ""

ingress:
  enabled: true
  class: "nginx"
  host: ""
  issuer: letsencrypt-prod
  annotations: {}

image: ghcr.io/openfaasltd/openfaas-oidc-proxy:0.0.2

replicas: 1

# OpenFaaS gateway URL
gatewayURL: http://gateway.openfaas:8080

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
